_layouts/default.html
_layouts/post.html
_layouts/screenshot.html

Page title section titles for Screenshots and News.
Uses a new frontmatter var in the relevant layout, and a conditional render-if-needed in default layout.

Truebraincrumbs

---

_layouts/default.html

Change copyright date to use site.time

---

_screenshots/0.4.7-africa.md

Also added a missing comma and minor grammar fixes.

typo fix: idillic -> idyllic

---

.gitmodules
_layouts/download.html
azure-pipelines.yml
static/js/download.js
static/js/ua-parser.js

This is not perfect, and it falls back to 'all files' pretty quickly.
It just helps with the 90% cases, namely: Windows and Mac OS.
Fixes #10.

Add: detect based on User-Agent which download the user wants most likely

---

README.md

Update: README.md is now more verbose and even contains a FAQ

---

pages/index.html
pages/screenshots.html

Several fixes for frontpage

---

nginx.default.conf

Mostly google indexed a few URLs in a way we did not anticipate.

Fix: also redirect some older URLs to the correct locations

---

_download-meta/openttd-pullrequests.md
fetch-downloads.py

This makes it easier to give a link to "latest".

Add: put openttd-pullrequests per Pull Request in its own folder

---

_posts/2019-02-10-1.9.0-beta2.md

Add: 1.9.0-beta2 release news post

---

_posts/2019-03-01-monthly-dev-post.md

[Rendered](https://github.com/OpenTTD/website/blob/monthly-dev-post/_posts/2019-03-01-monthly-dev-post.md)

Monthly Dev Post of March 2019

---

_posts/2019-03-01-monthly-dev-post.md

"post" --> "posts"
Very minor; just a quick typo fix

Update first monthly dev post

---

_posts/2019-04-01-monthly-dev-post.md

[Rendered](https://github.com/OpenTTD/website/blob/monthly-dev-post/_posts/2019-04-01-monthly-dev-post.md)

Add: Monthly Dev Post of April 2019

---

_posts/2019-05-01-monthly-dev-post.md

To edit or view the current result:
https://github.com/OpenTTD/website/blob/monthly-dev-post/_posts/2019-05-01-monthly-dev-post.md

Add: Monthly Dev Post of May 2019

---

static/css/base.css

It makes it wider than content, but it looks better than now anyway..
Modified it to use flex layout too.

Fix overflowing nav

---

_layouts/default.html

It's considered good practice to indicate the language of the content.

Add HTML lang attribute

---

static/css/page.css

It inherits its width from element main. No need to nail it to a particular value.
For details see #127.

Fix: remove fixed width of element #section-full

---

pages/donate.html

Fix: New EUR bank details on donation page.

---

.dorpsgek.yml
.github/workflows/deployment.yml
.github/workflows/publish.yml
.github/workflows/testing.yml

This makes the workflows a lot more readable, and other repositories
will use the same actions.

Add: [Actions] switch to our own actions instead of writing them out

---

static/css/index.css

Apparently Edge doesn't like `#00000000` colour codes. Seems happier with rgba though.

Fix banner background with Edge

---

_posts/2020-04-01-openttd-1-10-0.md

Comments appreciated. Also have a look through the changelog, see if there's anything major I've missed

Add: News post for 1.10.0

---

_data/download-descriptions.yml

~~And also put the 18.04 download description in the proper place~~

Add: Download description for Ubuntu 20.04

---

_posts/2020-06-01-openttd-1-10-2.md

#159 should be merged for 1.10.2 as well

Add: 1.10.2 release announcement

---

_posts/2020-12-01-infrastructure-migration-finished.md

[Rendered](https://github.com/TrueBrain/OpenTTD-website/blob/aws/_posts/2020-12-01-infrastructure-migration-finished.md)

Add: news post about finishing aws migration

---

_data/download-descriptions.yml

Add a description for the debug symbols for ARM64

Fix: Add description for ARM64 .pdb

---

_data/download-descriptions.yml

Add the zip version and relabel the DMG for clarity

Change: Add zip variant for macOS 10.9+ binaries

---

_contact/distribution.md

I will have another stab at getting a code signing certificate for Windows shortly. Before I do that, I want to advertise the company phone number in a hopefully quiet corner of the web site, as they seem to rather insistent on having a phone number advertised.

Add: Section in Contact page relating to OpenTTD Distribution Ltd

---

_posts/2021-06-10-openttd-on-gog

On twitter/reddit/discord I want to post:
``` 
OpenTTD now available on GOG.com! <link to our site>
```
I won't be posting this on Steam, as .. well .. duh :)

Add: news about OpenTTD on GOG.com

---

_posts/2021-06-10-openttd-on-gog.md

I found a cheap deal offer for a "r" and a "t". Do you want them?

Fix: typos in news post

---

.dorpsgek.yml
.github/workflows/publish.yml
.github/workflows/testing.yml
README.md

After approval, I will rename the branch, retrigger the checks, and merge this after.

Change: [GitHub] switch default branch to "main"

---

Gemfile.lock

addressable dependabot warning

Update: Gemfile.lock

---

_posts/2021-08-15-openttd-1-12-0-beta1.md
_posts/2021-08-15-openttd-12-0-beta1.md

Reddit: just the link: https://www.openttd.org/news/2021/08/15/openttd-12-0-beta1.html
Discord:
```
Hi @everyone,
I noticed it was over three months since we made our last release. Unacceptable. So it is time we start our OpenTTD 12 release cycle. Let's start with a beta .. just to make sure we didn't make any big boo-boos.
What is new you ask? Owh, just a way for you to play together really easy with your friends. Forget about port-forwarding .. just .. forget about it. Never again.
Not a multiplayer fan? No worries, we got plenty of other new features for you! Maybe you want to try a game with 255 NewGRFs?
Please report any issues you find with this beta in the usual place. It helps a lot getting the next stable out quickly and as bug-free as possible! …
```

Add: 12.0-beta1 announcement

---

_posts/2021-09-26-new-multiplayer-experience.md

I had to rewrite several parts several times, to not make it very lengthy / technical, but it is still very lengthy :P
I still think it is worth posting, even being this lengthy, to help people understand a bit what has changed / going on.
[Rendered view](https://github.com/OpenTTD/website/blob/multiplayer-experience/_posts/2021-09-26-new-multiplayer-experience.md)

Add: news post about new Multiplayer Experience

---

.dockerignore
.gitignore
README.md
_config.yml

While working on another PR, I noticed the README was a bit out of date. Also found some other bits and pieces that weren't as good as they can be. So you get them in a single PR to deal with :D

Fix: outdated information in README

---

_posts/2021-11-08-openttd-12-1.md

¯\\\_(ツ)_/¯
For twitter:
```
Bug fix release time! 12.1 is now available on GOG / Steam / our website!
https://www.openttd.org/news/2021/11/08/openttd-12-1.html
```
```
Bug fix release time! 12.1 is now released!
https://www.openttd.org/news/2021/11/08/openttd-12-1.html
```
Steam:
Same as the post

Add: 12.1 release announcement

---

_posts/2022-10-31-openttd-13-0-beta1.md

Fix: Typo in 13.0-beta1 announcement.

---

_screenshots/special-gamestar.md

Roman from TT-MS discovered, which issue of GameStar featured the article about OpenTTD 0.3.4.

Update: TT-MS rediscovered the source of this magazine article.

---

_posts/2023-06-10-openttd-13-2.md

I don't think it is worth making a full blog-post about this. Just a small modification is, in my opinion, sufficient.

Add: update 13.2 release post to mention 13.2.1

---

_posts/2023-07-08-our-infrastructure.md
_posts/2023-07-09-infra-migration.md

@LordAro was asking about more details of our infrastructure, and what all the migration talk was about. So I thought it would be good to put that in a blog post, for all to read.
It became too much for one post, so I made it into two.
The intention of these posts is:
- Awareness for the complexity of our infra
- Awareness of our monthly bill
- Awareness for our donation page
All that as I hope to avoid a fundraiser, as I just hate those :P
To read the rendered text, follow the Deployment link, or:
https://pr-267.openttd-website-2fx.pages.dev/news/2023/07/08/our-infrastructure
https://pr-267.openttd-website-2fx.pages.dev/news/2023/07/09/infra-migration

Add: two posts, one about our infrastructure, and one about our recent migration to it

---

_download-meta/openttd-branches.md
_download-meta/openttd-nightlies.md
_download-meta/openttd-releases.md
_download-meta/openttd-useful-releases.md

Some links were broken, other information was no longer current.

Fix: update meta-information for downloads

---

_download-meta/discord-social-releases.md
_download-meta/gog-galaxy-social-releases.md
_download-meta/openttd-branches.md
_download-meta/openttd-nightlies.md
_download-meta/openttd-releases.md
_download-meta/steam-social-releases.md

I kept the text simple and to the point, but I am welcoming any improvements to the text.
Steam and GOG Galaxy aren't actually available yet, but that will be done soon after merging this PR.

Add: metadata for Social Plugins, and references to them from OpenTTD download page

---

_posts/2024-02-18-openttd-14-0-RC1.md

Here's some draft for the first release candidate announcement.

Add: 14.0-RC1 announcement

---

.github/PULL_REQUEST_TEMPLATE.md

It is easy to forget we don't only need a post on this website, but also for other places. Reminder people with a small text :)

Add: [GitHub] PR template to remind people to attach Steam image / Social Text

---

_posts/2024-03-06-happy-birthday.md

To be published on Wednesday (6th).
Should probably go onto Steam and social networks too, I'll need to come up with a suitable image...

Add: Birthday blog post

---

_posts/2024-03-23-openttd-14-0-RC3.md

Content-less announcement proposal for RC3.
```
Features: added. Gameplay: improved. Bugs: squashed. Final testing pre-release: probably, unless time is [accidentally stopped]([https://www.openttd.org/news/2024/03/23/timekeeping).
Full details: https://www.openttd.org/news/2024/03/23/openttd-14-0-RC3
```

Add: Release post for 14.0-RC3

---

_posts/2024-12-24-openttd-15-0-beta1.md

Fix: link of changelog in the 15.0-beta1 news post

---

_posts/2025-04-13-openttd-15-0-beta2.md

Fix: Changelog is Markdown now (take 5465)

---

_screenshots/0.4.8-lots_of_goods.md

Fix typo (can->can't)

---

_layouts/download.html

Fix: use the changelog filename from the manifest
