Dockerfile
Gemfile
Gemfile.lock

Also bumped Jekyll while fiddling with Gemfile.

 Fix: for yet-unknown-reasons 'bundle install' no longer installs http_parser.rb and safe_yaml

---

_data/download-descriptions.yml
_layouts/download.html

Normally this was done via manifest.yaml, but for this the
descriptions had to be defined on the CDN, which is a weird place.
A better place is inside the repository that uses it, read: this
repository.

Add: lookup the description based on the extension

---

nginx.default.conf

Fix: also redirect serverlisting pages to their own subdomain

---

_download-meta/catcodec-releases.md
_download-meta/grfcodec-nightlies.md
_download-meta/grfcodec-releases.md
_download-meta/nforenum-releases.md
_download-meta/nosound-releases.md
_download-meta/opengfx-releases.md
_download-meta/openmsx-releases.md
_download-meta/opensfx-releases.md
_download-meta/openttd-nightlies.md
_download-meta/openttd-releases.md
_download-meta/openttd-useful.md
_download-meta/osie-releases.md
_download-meta/pngcodec-releases.md
_download-meta/strgen-releases.md
_layouts/default.html
_layouts/download.html
fetch-downloads.py

Binaries are uploaded to a CDN. listing.txt and latest.txt help
navigate the CDN.
Currently both infrastructures are supported. We will slowly
migrate everything to the new infrastructure, once everything is
live and in working order.

Add: support binary distribution via our new infrastructure

---

_download-meta/openttd-nightlies.md
fetch-downloads.py

The DigitalOcean CDN doesn't support IPv6.
proxy.binaries.openttd.org does, so redirect traffic via that
address. This is not optimal, but being reachable is more important
than being optimal.
Fixes #21

Fix: use proxy.binaries instead of direct CDN URL

---

nginx.default.conf

We cannot trust any URL to give a correct response, as we are not
in control of that data.

Add: url for health probe, which always returns 200

---

_data/download-descriptions.yml

Although this list contains anything we ever used, lets not add
things that we once considered using :)

Remove: -docs-source.tar.xz was never in production

---

_layouts/default.html
fetch-downloads.py

This meant 'stable' could become '1.9.0-beta1', which is never
what we want.

Fix: 'testing' and 'stable' were always the latest version

---

_layouts/default.html

In that case, we need to show the nightly version slightly different.

Fix: in a very rare case, it might happen nightly version == testing version

---

_posts/2019-02-25-1.9.0-beta3.md

The CDN is IPv4 only. The proxy.binaries URL routes traffic
correctly, depending if you are IPv4 or IPv6. Please avoid
public links to CDN directly.

Fix 7038a71: link to changelog was incorrectly pointing to the CDN directly

---

_config.yml
_includes/post_macro.html
_posts/2019-03-01-monthly-dev-post.md
pages/index.html
pages/news_archive.html

For example, the latest monthly dev post was so huge, that it didn't
really fit the look and style of the frontpage. A "read more" link
seems to patch up that issue for now.

Add: "read more" link for large posts on the frontpage

---

pages/donate.html

Prioritise bank transfers over PayPal, and add new bank details (separate accounts for EUR and USD to save on currency conversion fees)

Update: New bank details for donations

---

pages/development.html

Swapped the link to a wiki page that isn't deleted.  Fixes #75

Fix: 'development environments' link was broken #75

---

static/css/base.css

Fix: Remove extra padding-top for download headers

---

_layouts/default.html

- removed the second charset encoding declaration, was doubled
- moved a space in the title element, following the change in #80
This should IMHO not need further discussion and will definitely not break anything.

Two small changes with only a small effect to the output 

---

_includes/post_macro.html
static/css/page.css

As proposed in #82 the blog article template was reorganised as `<article>` with a `<header>` that contains the heading and the meta data (time and authors name) and the `div.content`.
**Optical changes**
- the blog articles meta data got their own text line below the articles heading; this could be reset to right aligned after the rework of the whole site with a mobile aware and responsive design (stays below heading on narrow viewports and moves to the right side on wide viewports)
- the `<header>` got a dotted `border-bottom` as separator from the articles content
- the border of the header and also the border of the content got an a bit darker colour (`#d8d8d8` instead `#eee`)
**Further change under the hood**
- the read-more-link got an own paragraph
I kept the rules for …

Change: HTML5-elements and corresponding CSS-rules for the blog article template

---

.dorpsgek.yml

Mirror OTTD's dorpsgek.yml file. Not that I'm sure why DorpsGek would manage to commit to the repo...
(Sorry about the local branch creation, forced by GH UI...)

Change: Don't push push notifications to IRC

---

_posts/2019-10-26-monthly-dev-post.md

All the other monthly dev posts say "Monthly Dev Post of (MMMM) (YYYY)", but this didn't have the "of".

Fix typo/inconsistency in October monthly dev post

---

_data/download-descriptions.yml
_layouts/download.html

I don't really know how the website works, but I think it would be nice to have an easy access to pdb files. I hope this change is enough.

 Add: 'Developer Files' section on download pages 

---

Dockerfile

Docker build is broken since december 16th (rubygems updated from 3.0.6 to 3.1.1, including an update for bundler from 1.17.3 to 2.1.0).
I don't know if it's the right fix, but it works :)
Other option is to install older bundler.

Fix: update bundler version

---

static/css/base.css

It caused non-centered header and content blocks because they have own different fixed width.

Remove width from body

---

.github/workflows/deployment.yml
.github/workflows/publish.yml
.github/workflows/testing.yml
Dockerfile
fetch-downloads.py
nginx.default.conf

This is still a WIP. Missing:
(yes, this deprecates the use of Azure Pipelines)
I am going to change how tags are created on the images. The master branch will have the tag `dev` (and `development`), and it will overwrite this tag. The tags will have the tag (wit for example `1.1.18`): `1`, `1.1`, `1.1.18`, and here too it will overwrite these tags when rebuild/published. This means tags will no longer contain the date of when they were published. This will now be inside the docker image as a `LABEL`. See [here](https://hub.docker.com/r/openttd/website/tags?page=1&ordering=last_updated) to understand why the current system is not working :)
This means that production needs to fetch the latest tag, which can be a bit unclear. So, instead, we are going to deploy based on the `sha256` tag. …

Various of fixes in preparation of running this Docker on AWS

---

README.md

We are using shields.io, as they are awesome. They also allow more
badges, so added a few extra; mostly because I could.

Fix: replace the Azure Pipeline badges with GitHub badges

---

.github/workflows/publish.yml

When merging a second pull-request while the first has not created
a deployment yet, the 'refs/heads/master' resolves to the wrong
sha-hash, showing the wrong commit being deployed (it deploys the
commit of the first, while showing it did the one of the last).

Fix: use a sha instead of 'refs/heads/master' as ref for deployments

---

static/css/base.css

The widths of the elements `main` and `footer` was broken (narrower than `header` and `nav`) because the width was only `776px` instead the `800px` of `header` and `nav` and in contrast to `header` and `nav` `main` and `footer` have a padding for their content which is part of the width calculation.
So the `main` and `footer` boxes had (as first issue) not the same width as `header` and `nav` and had (as second issue) a resulting width of `814px`when the rule for the box width said `width: 800px;` because the `7px` for `padding-left` and `padding-right` got added to the `800px`of the width-rule. 
The correction was done with changing the box model to border-box (which includes paddings and border-widths in the width calculation for the element). Additionally the width rule for the direct …

Fix: correct the width of main and footer

---

static/css/base.css
static/css/index.css

Until now the CSS lacks rules for the pseudo class `:focus` for links. Because of that a keyboard user, who steps through the links, sees – in the best case – only the dotted outline. I added the `* a:focus` selectors where I found a matching selector for `* a:hover`. Now one, using the keyboard, sees the same formats as another one, using the mouse (cursor).
Additionally I added the general selector `a:focus, a:hover` for all links in text sections that got no formats from elsewhere. That way one can remark the focussed or hovered link by the dotted outline *and* the changing text colour.

Make the website better navigable with keyboard

---

_layouts/download.html
_layouts/post.html
_layouts/screenshot.html
pages/404.html
pages/50x.html
pages/about.html
pages/contact.html
pages/development.html
pages/donate.html
pages/index.html
pages/news_archive.html
pages/policy.html
pages/screenshots.html
static/css/index.css
static/css/page.css

It started as pure fixes but landed as medium changes.
- adjusted the padding of the headings (`h3`) to leave place for the icons
- remove the margin from the headings and put a right padding to the containing `div` instead (same `10px` as left padding)
- remove all `div.section-icon` and put the icon to the headings itself, removed also the CSS-ruleset for `div.section-icon`
That makes the HTML-structure a bit smaller and simplifies the CSS-ruleset a bit
- replace the overly nested structure with `div`s with a `figure`-`figcaption` combination (HTML5 rules)
- removed the `div` for the `a` and the `img` in it and give its task directly to the `a`
- removed the height from `#screenshot-image` because the fixed height in combination with the `box-model: border-box;` caused the break …

Padding corrections as consequences of #130

---

static/css/index.css

It was spaced a bit too far to the left, which made it look off.
Old result:
New result:

Fix: better margin of logo on the banner

---

_layouts/default.html
static/css/base.css

Because of the rtl-issue, desccribed in #117, I began to rework the header section. Follwoing changes are part of the PR.
- organised the header as a flexbox
- rebuilt the download-fast-box as a list
- simplified the structure of the logo-container
- putting all background-related rules (image, position, size) into the shorthand `background`
- removed several height and width values because the boxes takes the necessary space themself
I have a question about tha last point. I added the whole list of selectors whose names begins with `#openttd-logo-text` but I have no clue if some of them might be not in use here. Some of them i.e. like *-bananas, *-noai seems to be intended for use on different subdomains. Are there selectors I can remove without breaking things on another place? …

More or less complete rework of the page header

---

.github/workflows/publish.yml
README.md
static/css/base.css

Two totally unrelated fixes, but I was lazy. Sorry.
Old banner:
New banner:

Fix version detection, top-left banner, and add deployment badges

---

_layouts/default.html

This is because there was a / missing after "baseurl", which is
present for all other links.
Fixes #139

Fix: logo in top-right corner wasn't pointing to "Home"

---

pages/development.html

All documentation is now available on https://docs.openttd.org/.

Fix: links to documentation have changed

---

nginx.default.conf

As we no longer publish non-latest on the website, send them to
somewhere where the files are still available.
Fixes #149

Fix: redirect non-latest releases to the CDN directly

---

static/css/base.css

See OpenTTD/website#117
They were originally lopsided, but now it's about equal on both sides.
Before:
After:

Fix: paddings in website footer

---

_config.yml

The site is available on that particular URL, so include it on the URL configuration.
This should fix the errors I get on the feed generation.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.openttd.org%2Ffeed.xml
The feed itself does not validate, but this is kinda strange, because my feed reader accepts with weird post URLs.

Include final URL

---

Dockerfile

Completely unexpected, all of a sudden we need an additional
depenendency for "gem update" to work. We don't know why or when,
all we know the Docker no longer wants to build. This fixes the
problem.

Fix: also install ruby-etc in order for "gem update" to work

---

_data/download-descriptions.yml

Refer to "macOS" and label the binaries as universal.

Fix: Add Universal description for modern macOS binaries

---

_data/download-descriptions.yml
static/js/download.js

This displays a description for ARM64 binaries (Windows 10) and also adds autodetection, which unlike on Mac should actually work...

Feature: List Windows ARM64 binaries correctly, autodetect ARM64 Windows

---

static/js/download.js

We renamed "macosx" to "macos" but I missed this change, sorry.
The only potential issue I can see is that this may break the detection on the stable build (until we release 1.11), but there's only one macos image anyway so it shouldn't be hard for users to pick the right one.

Fix: Autodetect macOS correctly

---

_data/download-descriptions.yml

Our builds no longer function on Windows XP. XP has been out of support and is 20 years old this year. We didn't support Windows 2.0 in 2005, so I don't think we need to support Windows 5.1 in 2021!

Fix: Windows XP is no longer supported

---

_data/download-descriptions.yml

Just had a query whether macOS 11/M1 was supported by the new universal builds. Make it clear that this is the case.
Bikeshedding!

Change: Make it clearer that macOS 11 is supported

---

_config.yml
_contact/abuse.md
_contact/bugs.md
_contact/development.md
_contact/features.md
_contact/general.md
_contact/questions.md
_people/abuse.md
_people/adf88.md
_people/alberth.md
_people/belugas.md
_people/frosch.md
_people/general.md
_people/glx.md
_people/matthijs.md
_people/michi_cc.md
_people/orudge.md
_people/peter1138.md
_people/planetmaker.md
_people/rubidium.md
_people/smatz.md
_people/terkhen.md
_people/truebrain.md
_people/yexo.md
_people/zuu.md
pages/contact.html

It no longer shows email-addresses of Developers, but instead
gives a whole bunch of places people could go to for the contact
they are looking for.
This is mostly triggered by the increased amount of questions
we get at info@, which is not a place you will receive an answer
from.

Add: rework our "Contact" page

---

_posts/2021-03-15-openttd-1-11-titlegame-voting.md

Voting for the 1.11 title screen will begin later today. Voting will be open for about two weeks, and TrueBrain said a news item is fine with him.

Add: 1.11 Title screen voting announcement

---

_posts/2021-03-22-livestream-2-april.md

We're going live on Twitch again! I volunteered to write this post and make an announcement on Reddit. (Who is writing the Discord announcement?)
TrueBrain said the livestream will be at 2000 CEST, which [worldtimebuddy](https://www.worldtimebuddy.com/) says is 18:00 UTC.

Add: Announcement for April 2 livestream

---

_posts/2021-04-03-livestream-9-april.md

Announcement for the planned Q&A stream on April 9th.
YouTube link for last livestream needs to be filled in or removed.
Attendance list to be confirmed.

Add: Announcement for April 9 livestream

---

_screenshots/0.7-Slintfield_Transport_michael_schulze_XX_20090524.md

Noticed it in the website build in-between 1.11 being released & the news post being deployed :)

Fix: Typo in screenshot description

---

.github/workflows/deployment.yml

GitHub added a cool new feature, that finally removes us humans having to think about this.
Now you can just go nuts with merges and releases etc, GitHub will prevent 2 deployments happening at the same time (which error out on AWS).

Fix: [Actions] prevent multiple deployments at the same time

---

_posts/2021-05-03-openttd-1-11-2.md

Kept it simple, as .. it is just a patch release.
Reddit: just the link: https://www.openttd.org/news/2021/05/03/openttd-1-11-2.html
Discord:
```
Hi @everyone,
OpenTTD 1.11.2 has just been released!
Now users with Intel GPUs should be able to enjoy the game too!
Owh, and also a bunch of bug-fixes while we were at it.
https://www.openttd.org/news/2021/05/03/openttd-1-11-2.html
```
Twitter:
```
OpenTTD 1.11.2 now available on Steam / our website.
More bugfixes! And it now should run fine on Intel GPUs too!
https://www.openttd.org/news/2021/05/03/openttd-1-11-2.html
```
tt-forums, update on 1.11 post:
```
OpenTTD 1.11.2 is now ready for download!
```
Steam: website post, with this image:

Add: 1.11.2 release post

---

.github/workflows/publish.yml

Without this, it is possible that a newer job builds faster and
deploys before the older job, reverting the website to an old
state.

Fix: [Actions] queue publish jobs so they are executed in order

---

.github/workflows/cloudflare-pages-production.yml
.github/workflows/cloudflare-pages-staging.yml
.github/workflows/release.yml

Scripts are very simple:
- On trigger to build main/latest, call Deploy Hook on Cloudflare Pages
- On release, copy "main" to "production"
Cloudflare Pages takes care of the rest.
Not deployed live yet, the "shadow" URLs are:
https://www-test.openttd.org/
https://www-staging-test.openttd.org/

Add: [Cloudflare Pages] automation to deploy website to Cloudflare Pages

---

Dockerfile

Building the docker container fails due to missing "bundle".
Looks like alpine cleaned up some dependencies, so it was no longer installed via other packages.

Fix: ruby-bundler is no longer installed indirectly, add it explicitly.

---

_posts/2022-04-02-openttd-12-2.md

For twitter:
```
Late April Fools! 12.2 is now available on GOG / Steam / our website!
https://www.openttd.org/news/2022/04/02/openttd-12-2.html
```
Reddit:
```
Late April Fools! 12.2 is now released!
https://www.openttd.org/news/2022/04/02/openttd-12-2.html
```
Steam / Discord / tt-forums:
Same as the post

Add: 12.2 release announcement

---

_data/download-descriptions.yml

On the downloads page the latest version of Windows isn't mentioned. I don't know whether OTTD works on Windows 11, but opened this PR to draw attention to the possible omission of this version and to discuss whether support is warranted.

Advertise Windows 11 support

---

_posts/2022-10-31-openttd-13-0-beta1.md

Preview: https://release-13-beta1.openttd-website.pages.dev
```
Halloween is around and we want to clean out the cutting room floor.
I can offer you the first testing release of the 13.X release series containing the results.
We found some nice improvements like building objects by dragging or better rivers on map generation.
The UI got some polish, too, both by having some improved windows in-game and a by a better handling of HiDPI contexts.
Go check it out today and help us break the game!
https://www.openttd.org/news/2022/10/31/openttd-13-0-beta1.html
```
For twitter:
```
OpenTTD 13.0-beta1 now available on Steam / our website.
Drag objects all over the place and help us break the game.
https://www.openttd.org/news/2022/10/31/openttd-13-0-beta1.html
``` …

Add: 13.0-beta1 announcement

---

_posts/2022-11-27-openttd-13-0-beta2.md

Reddit / Discord/ TT-Forums:
```
Multiple beta releases often indicate lots of bugs to be fixed, but in this case we got carried away adding features and thought more testing was needed.
The big new feature is variable interface scaling, not just at 2x and 4x, with chunky bevels for that retro feel! We've also made multi-track level crossings safer, changed the World Generation menu to make NewGRF, AI/ and Game Script configuration more convenient, and made several enhancements to vehicle lists.
Go check it out today and help us break the game!
https://www.openttd.org/news/2022/11/27/openttd-13-0-beta2.html
```
For Twitter (if it's still around 😛 ):
```
OpenTTD 13.0-beta1 now available on Steam / our website.
Resize the game interface to your liking and check out the new chunky bevels! …
```

Add: 13-beta2 announcement

---

_posts/2023-01-01-openttd-13-0-rc1.md

Preview: https://release-13-rc1.openttd-website.pages.dev
```
The next year has come and with it the feature freeze for the 13.X release series.
The new 13.0-RC1 testing release brings various fixes and a few new features like NewGRF vehicle variants.
Go check it out today and help us find any last minute bugs!
Available on Steam / GOG / our website as usual.
https://www.openttd.org/news/2023/01/01/openttd-13-0-RC1.html
```
For twitter:
```
New year, new OpenTTD, one step closer to 13.0.
OpenTTD 13.0-RC1 now available on Steam / GOG / our website.
https://www.openttd.org/news/2023/01/01/openttd-13-0-RC1.html
```
Steam:
Insert nice image here.

Add: 13.0-RC1 announcement

---

_posts/2023-01-28-openttd-13-0-rc2.md

Preview: https://release-13-rc2.openttd-website.pages.dev
```
We found some bugs in the 13.0-RC1 testing release that need cleaning up.
The new 13.0-RC2 testing release should fix these and bring us into the home stretch for a final release.
Go check it out today and help us find any last minute bugs we don't know about yet!
If you are a translator, we'd appreciate your help for a translation check before the final release.
https://www.openttd.org/news/2023/01/28/openttd-13-0-rc2.html
```
For twitter:
```
OpenTTD 13.0-RC2 now available on Steam / GOG / our website.
Last minute fixes before a full release.
https://www.openttd.org/news/2023/01/28/openttd-13-0-rc2.html
```

Add: 13.0-RC2 announcement

---

_posts/2023-02-05-openttd-13-0.md

Preview: https://release-13-0.openttd-website.pages.dev
```
Breaking news: OpenTTD 13.0 is finally available! Depending on your perspective, we’re either two months early for our usual April 1st release, or a bit tardy for the Christmas 2022 release we intended.
This version brings numerous additions to the game, both on the UI side and on the gameplay side.
Highlights include fractional interface scaling, NewGRF engine variants, multi-track level crossings and various UI improvements.
For the full story, see the release announcement: https://www.openttd.org/news/2023/02/05/openttd-13-0.html
```
For twitter:
```
Breaking news: OpenTTD 13.0 now available on Steam / GOG / our website.
Get all the new features now! …
```

Add: 13.0 release announcement

---

_posts/2022-04-10-openttd-13-1.md

Reddit/Discord/TT-Forums:
```
OpenTTD 13.0 has been out for two months and we've found some bugs to fix in 13.1! Most notably, we've fixed two kinds of crashes:
* Road vehicles inside multi-track level crossings no longer crash into the side of trains.
* The game no longer crashes when a spectator in a network game tries to interact with a town's local authority.
For NewGRF authors using the new engine variant feature, we've added a callback to select how the engine's name is displayed in the buy menu.
Go check it out and try not to crash!
https://www.openttd.org/news/2023/04/10/openttd-13-1.html
```
Twitter:
```
OpenTTD 13.1 now available on Steam / our website.
Road vehicles no longer crash into the side of trains!
https://www.openttd.org/news/2023/04/10/openttd-13-1.html
```
Steam: …

Add: 13.1 release announcement

---

_posts/2023-05-14-policy-and-survey.md
pages/policy.html

Together with https://github.com/OpenTTD/survey-web/pull/1, I like to publish this blog + policy update.
Basically, the policy was written in a time we had to deal with useraccounts and emails etc etc. It is scary how little information we process these days, and we might as well write that in our policy.
It does require the above mentioned PR to be merged first, as https://survey.openttd.org is an empty page now :)

Add: update policies and blog about automated opt-in survey

---

pages/donate.html

Liberapay offers a free method for setting up and managing subscriptions (unlike, for instance, Patreon), which has been requested by at least one donor. Doesn't seem to be any reason not to try it.

Add: Add link to Liberapay on the donation page

---

pages/donate.html

Accidentally added an unnecessary 's' when adding the new Liberapay section to the donate page.

Fix: Use correct class for Liberapay <div>

---

static/css/base.css

Making the body being a flexbox makes it possible to enlarge the element `main` to the complete viewport height (except the heights for `header`, `nav` and `footer`). This is only an issue on pages with very little content. Longer pages, that stretches the content over the whole viewport by itself, are not affected.
Screenshot 1 shows the donation page, scaled to 67% without the flexbox.
Screenshot 2 showns the same page, same scale as in screenshot 1 with the flexbox stretching the element `main`.

Change: make even short pages take the whole viewport height

---

.github/workflows/publish.yml

The alias domain is the same for the same Pull Request, no matter how often you push. This makes sharing the link easier.
While at it, rename "pull/N" to "pr/N", as it is a pull request; not a pull.
For the curious, see: https://github.com/cloudflare/pages-action#outputs

Fix: [CI] use alias as deployment URL

---

.github/workflows/testing.yml

Basically, I broke the promise the API of an action / reusing workflow shouldn't change with the same major. As I did change things. Oops. This should fix it .. I hope :)
Edit: it does \o/

Fix: [CI] upstream actions changed property names

---

_layouts/default.html
static/css/base.css

Rework the page footer to a more modern structure.
Replace it with a flexbox solution. That way we get rid of the floats, that are technically meant as a solution for floating an elements content around an element (group) but was used as a workaround for placing block elements in their parent boxes without nailing their position for many years. Nowadays we have much better solutions (flexbox or grid) with a wide and stable browser support.
Was a `div` with bare links and is now rebuilt as a real HTML-list.
I did this because the pipes (`|`) between the link titles are no content of the document but decoration for displaying it in a graphical browser. When the characters are in the HTML-source, a screenreader would read the pipes between the link titles but when inserted with CSS – as …

Rework of the footer

---

_posts/2023-06-10-openttd-13-2.md

Reddit/Discord/TT-Forums:
```
As I write this many of the development team and other members of the community are busy having fun at a meet-up in Brussels. Not me though, I'm stuck here doing a release.
We've been busy refactoring quite a lot of the underlying code to make future changes easier, but along the way we've found and fixed a few more bugs and quality of life improvements that we figured were worth releasing sooner than whenever 14.0 comes along.
Notably, hardware acceleration should automatically disable itself if it detects an issue (crash) while initialising, and plenty of other crashing bugs have been fixed too.
Go check it out!
https://www.openttd.org/news/2023/06/10/openttd-13-2.html
```
Twitter:
```
OpenTTD 13.2 now available on Steam / our website. …
```

Add: 13.2 release announcement post

---

_posts/2023-06-11-openttd-13-3.md

For Discord:
```
@everyone
Oops .. turns out 13.2.1 didn't go as well as planned. So we made 13.3, which mostly aims to make sure multiplayer is working as expected again.
Want to read the full story? https://www.openttd.org/news/2023/06/11/openttd-13-3.html
```

Add: 13.3 release announcement post

---

_posts/2023-06-10-openttd-13-2.md

13.3 is a rebrand of 13.2.1, so no need to mention 13.2.1 anymore.
Fixes #265

Fix: remove any mention of 13.2.1

---

_posts/2023-07-29-openttd-13-4.md

Reddit/Discord/TT-Forums/Twitter (RIP)/Mastadon?/Etc?:
```
OpenTTD 13.4 now available on Steam/our website to fix a crash when a news item appears while a drop-down menu is open.
https://www.openttd.org/news/2023/07/29/openttd-13-4.html
```
Steam:
[News.-.13.4.release.zip](https://github.com/OpenTTD/website/files/12208022/News.-.13.4.release.zip)

Add: Release announcement for 13.4

---

_posts/2023-07-08-our-infrastructure.md

As this story is meant to be read in a year or in 3 years from now, to get an idea how our infra run, let's make sure it is somewhat up-to-date.

Fix: Cloudflare R2 API keys can be scoped per bucket now

---

_posts/2024-02-03-openttd-14-0-beta1.md

I kept the announcement simple and small. For 14.0 (see other PR) I do suggest we explain in much more detail what is going on. But doing that now feels premature, and ruining the party.
@2TallTyler promised to make a blog-post about daylength, but that will be its own post.
For now I mostly need help, someone creating a 14.0-beta1 release image for Steam.
Reddit/Discord/TT-Forums/Twitter (RIP)/Mastadon?/Etc?:
```
OpenTTD turns 20 this year, and to celebrate we are preparing for one of our largest ever releases.
It's packed with 40 new features, 80 changes, and almost 150 fixes.
In the upcoming weeks we will share more posts explaining some of these features in depth. For now, we need your help testing our work.
We need as many people as possible to test this beta version of the 14.X …
```

Add: 14.0-beta1 announcement

---

_posts/2024-02-04-openttd-14-0-beta2.md

Crashes are bad.
Reddit/Discord/TT-Forums/Twitter (RIP)/Mastadon?/Etc?:
```
You found some bugs in the beta1-release, and we found a new beta.
With this update, you can now safely signal to your hearts content again.
We need as many people as possible to test this beta version of the 14.X release series, so you can find and we can squash as many bugs as possible before the actual release.
https://www.openttd.org/news/2024/02/04/openttd-14-0-beta2
```

Add: 14.0-beta2 announcement

---

_posts/2024-02-06-openttd-14-0-beta3.md

Well, if anybody feels like making a release, here's a news message proposal. Don't forget to fix the posting date as needed.
Reddit/Discord/TT-Forums/Twitter (RIP)/Mastodon?/Etc?:
```
Well, third time's the charm, or so they say.
With the 3rd beta of OpenTTD 14, we've restored the cargo types that went missing from some climates.
Please come with us on the treasure hunt for bugs, so OpenTTD 14 can become the best OpenTTD ever.
https://www.openttd.org/news/2024/02/06/openttd-14-0-beta3
```

Add: 14.0-beta3 announcement

---

.github/PULL_REQUEST_TEMPLATE.md

Mention exact Steam image dimensions (800x450px) in PR template

Fix: [GitHub] Add exact Steam image dimensions to PR template

---

_posts/2024-03-16-openttd-14-0-RC2.md

Announcement for 14.0 RC2
Reddit / Discord // tt-forums
```
OpenTTD 14.0 is soon to be released. You guys already worked hard to break the game, and we've been working hard to fix the issues you've reported. Today we release RC2 with all of the recent fixes.
Please help us hunt down the last bugs, and make sure you're having fun doing it! Your help is greatly appreciated!
https://www.openttd.org/news/2024/03/16/openttd-14-0-RC2
```
Xitter:
```
OpenTTD 14.0-RC2 now available! Please help us hunt down the last bugs!
https://www.openttd.org/news/2024/03/16/openttd-14-0-RC2
```

Add: 14.0-RC2 announcement

---

_posts/2024-04-13-openttd-14-0.md

[Openttd_14_release.zip](https://github.com/OpenTTD/website/files/14942565/Openttd_14_release.zip)
Steam:
```
Welcome to 14.0!
OpenTTD's first release was in March of 2004.
Now twenty years later, we are proud to present to you: release 14.0.
<image>
And boy, what a release it is.
Do I dare to say: this has been the biggest release yet?
Sometimes people try to tell us OpenTTD is dead.
Well, 14.0 shows you it really isn't.
There are so many new goodies in 14.0, that I don't even know where to start!
Let's go over a few, just to get you a feel for what to expect when you launch OpenTTD 14.0.
```
Discord / Reddit / Mastodon / ...
```
Welcome to 14.0!
OpenTTD's first release was in March of 2004.
Now twenty years later, we are proud to present to you: release 14.0.
And boy, what a release it …
```

Add: Release announcement for 14.0

---

pages/donate.html

Bank transfers in the UK now generally require the account name to be provided, for validation. Scary warnings appear if you don't have this.

Change: Add account name for UK bank account (required for verification)

---

_posts/2024-12-24-openttd-15-0-beta1.md

Well, someone started with updating the changelog for a release, so let's motivate a bit more, just in case 😄 
Reddit/Discord/TT-Forums/Twitter (RIP)/Mastadon?/Etc?:
```
Ho, ho, ho, Santa is in town. And he's brought a gift with him.
The first beta version of the coming OpenTTD 15 release comes faster, with road waypoints, fewer passwords, better scenario editor, and hopefully with a lot less bugs.
There's a lot of bugs left for you to find, though, guaranteed. Enjoy the beta, test all the things and report anything you find amiss, to make OpenTTD 15 the best OpenTTD ever.
https://www.openttd.org/news/2024/12/24/openttd-15-0-beta1
```

Add: 15.0-beta1 announcement

---

.github/workflows/publish.yml
.github/workflows/testing.yml

Seems 3.0 is too old for latest Jekyll

Update: bump Ruby to 3.3

---

.github/dependabot.yml

Fix: name groups in dependabot for what they are

---

_posts/2025-03-29-openttd-15-0-beta2.md
_posts/2025-04-13-openttd-15-0-beta2.md

Long social message (Reddit / Discord / TT-Forums):
```
April 1st has come and gone, but have no fear, for a new OpenTTD 15 beta release is here.
It includes new features like an option to let players place town houses, more rocks, snowy rocks, and touchpad scrolling on Windows, plus a bunch of bugfixes.
Check it out and help us test!
https://www.openttd.org/news/2025/04/13/openttd-15-0-beta2.html
```
Short social message:
```
OpenTTD 15.0-beta2 now available on Steam / our website.
Place houses and look out for increased rocks.
https://www.openttd.org/news/2025/04/13/openttd-15-0-beta2.html
```
Steam:
Steam image below by Zephyris!

Add: OpenTTD 15.0-beta2 announcement

---

pages/index.html

Instead of leading you to the list of all screenshots, the featured screenshot will now lead you to its respective webpage.

Change: Display a larger resolution of the featured screenshot when clicked

---

_posts/2025-08-31-openttd-15-0-beta3.md

Long social message:
```
Having a lazy summer? Over at OpenTTD HQ, we are not!
We've been busy building bridges over stations, rerouting ships traveling in opposite directions, improving the user interface, adding support for NewGRF Badges, and fixing bugs.
Come help us test our work!
[link to OpenTTD.org news post]
```
Short social message:
```
OpenTTD 15.0-beta3 now available on Steam / our website.
You can now build bridges over stations!
[link to OpenTTD.org news post]
```
Steam image in the spirit of our new title game. 😄 
[News-15.0-beta3.zip](https://github.com/user-attachments/files/21181826/News-15.0-beta3.zip)

Add: OpenTTD 15.0-beta3 announcement
